version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/sqls:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - appnet
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - appnet
    restart: unless-stopped

  api:
    build: ./src/api
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    ports:
      - "3000:3000"
    networks:
      - appnet
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./src/api:/app/src
      - /app/src/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/config/nginx.conf:/etc/nginx/nginx.conf
      - ./src/config/ssl:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - appnet
    restart: unless-stopped

  osrm-router:
    image: osrm/osrm-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - osrm-data:/data
    networks:
      - appnet
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  osrm-data:

networks:
  appnet:
    driver: bridge
